#!/bin/bash

set -e
for br in $(git branch --contains 591463ae13f269d85bf0e5b3494961bf0b6b78b0 | grep '^. ' | sed 's/^..//'); do
	test "$br" = "master" && continue
	git checkout "$br"
	if ! git rebase origin/master; then
		git rebase --abort
	fi
done
